version: '3.7'
services:
    dynamodb:
        build:
            context: .
            dockerfile: Dockerfile.dynamodb
        restart: always
        healthcheck:
            test:
                ['CMD-SHELL', 'curl -f http://localhost:8000/shell/ || exit 1']
            interval: 1s
            timeout: 10s
            retries: 3
        ports:
            - '8000:8000'
        expose:
            - '8000'
        volumes:
            - dynamodb-local:/home/dynamodblocal/db

volumes:
    dynamodb-local:
        driver: local

networks:
    default:
        name: lambda
