# For persisting local DynamoDB data, from:
# https://www.mydatahack.com/how-to-persist-data-in-local-dynamodb-docker-container/
FROM amazon/dynamodb-local
WORKDIR /home/dynamodblocal
RUN mkdir ./db && chown -R 1000 ./db
CMD ["-jar", "DynamoDBLocal.jar", "-dbPath", "./db", "-sharedDb"]
VOLUME ["./db"]